RED = ("errfg", "wbg")
ORANGE = ("warnfg", "wbg")
BLUE = ("verbfg", "wbg")
GRAY = ("subfg", "wbg")
DARK_RED = ("srcstr", "wbg")
GREEN = ("srccmnt", "wbg")
WHITE = ("emphbg", "wbg")
YELLOW = ("srcdrct", "wbg")
LIME = ("wfg", "wbg")
LIME_HIGHLIGHT = ("wbg", "wfg")

def red(content): return colorize(RED, content)
def yellow(content): return colorize(YELLOW, content)
def orange(content): return colorize(ORANGE, content)
def blue(content): return colorize(BLUE, content)
def gray(content): return colorize(GRAY, content)
def dark_red(content): return colorize(DARK_RED, content)
def green(content): return colorize(GREEN, content)
def white(content): return colorize(WHITE, content)
def lime(content): return colorize(LIME, content)
def lime_highlight(content): return colorize(LIME_HIGHLIGHT, content)
def colorize(col, content): return "<col fg=\"{}\" bg=\"{}\">{}</col>".format(col[0], col[1], content)